export const WORKSPACE_PENDING_PREFIX = "WORKSPACE_PENDING_APPROVAL\n";
export const AGENTFLOW_FILE_PENDING_PREFIX = "AGENTFLOW_FILE_PENDING_APPROVAL\n";
export const COMPONENT_TYPE_PENDING_PREFIX = "COMPONENT_TYPE_PENDING_APPROVAL\n";
